name: Keepalive

on:
  # At 4:20 AM UTC, on day 13 of the month
  schedule:
    - cron: '20 4 13 * *'
  workflow_dispatch:

jobs:
  keepalive:
    name: Keepalive
    # Only run cron on the symbiote account
    if: (github.event_name == 'schedule' && github.repository_owner == 'symbiote') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
